version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"  # Changed to port 5173 for frontend
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://backend:5001
    depends_on:
      - backend
    networks:
      - pdf-suite-network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.backend.simple
    ports:
      - "5001:5001"  # Changed to port 5001 for backend
    environment:
      - NODE_ENV=production
      - PORT=5001
    volumes:
      - ./server/uploads:/app/uploads
      - ./server/temp:/app/temp
      - ./server/temp_pdf:/app/temp_pdf
    networks:
      - pdf-suite-network

networks:
  pdf-suite-network:
    driver: bridge 